#!/usr/bin/env bash

source "./lib/logger.sh"
source "./lib/builder.sh"
source "./lib/config.sh"

verificar_gcc() {
    if ! command -v gcc &> /dev/null; then
        log_erro "O GCC nao foi encontrado."
        exit 1
    fi
}

verificar_permissao() {
    if [[ ! -r "." || ! -w "." || ! -x "." ]]; then
        log_erro "Permissoes insuficientes no diretorio do projeto."
        exit 1
    fi
}

validar_comando() {
    local comando="$1"

    if [[ -z "$comando" ]]; then
        log_erro "Nenhum comando digitado { build / run / clean / rebuild / info }"
        exit 1
    fi

    case "$comando" in
        build|run|clean|rebuild|info)
            # comando valido, nao faz nada
            ;;
        *)
            log_erro "Invalido: '$comando'. Opcoes: { build / run / clean / rebuild / info }"
            exit 1
            ;;
    esac
}

verificar_permissao

COMANDO="$1"
validar_comando "$COMANDO"

log_info "Estrutura inicial rodando (arquivo cbuild)"
carregar_configuracao

case "$COMANDO" in
    build)
        verificar_gcc
        verificar_arquivos_c "$DIRETORIO_FONTE"
        construir_projeto
        ;;
    run)
        rodar_executaveis
        ;;
    clean)
        limpar_projeto
        ;;
    rebuild)
        verificar_gcc
        verificar_arquivos_c "$DIRETORIO_FONTE"
        reconstruir_projeto
        ;;
    info)
        exibir_info
        ;;
esac